import type { Metadata } from "next";
import { Geist, Noto_Sans_Lao } from "next/font/google";
import "./globals.css";
import { Providers } from "./provider/providers";
import Navbars from "./components/Navbar/page";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Noto_Sans_Lao({
  variable: "--font-noto-sans-lao",
  weight: ["100","200","300","400", "500", "700"],
  subsets: ["lao"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.className} font-sans antialiased`}
      >
        <Providers>
          <Navbars/>
          {children}
          </Providers>
      </body>
    </html>
  );
}
